name: Update Profile Pictures Cache-Buster

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch: # allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull origin main --rebase

      - name: Push changes
        run: git push origin main

      - name: Replace cache-buster in README.md
        run: |
          DATE=$(date +"%Y%m%d")
          sed -i "s/cb={{DATE}}/cb=${DATE}/g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update profile pictures cache-buster"
          git push
